// Package openvpn implements backend.Backend on top of N OpenVPN server
// subprocesses ("instances", see config.go), one per configured
// tag/proto/port combination - this backend's analogue of a sing-box/xray
// "inbound". See process.go's instanceProcess for the single-subprocess
// lifecycle (mirrors backend/singbox/core.go's Core, generalized to N-of
// instead of one) and management.go for the single biggest structural
// difference from every other backend in this repo: user membership is
// authenticated live over each instance's management-interface Unix socket
// against an in-memory map, instead of being baked into a config file - see
// user.go's doc comment for why this means SyncUser/SyncUsers/UpdateUsers/
// UpdateUsersAndRestart never need to restart a subprocess here, unlike
// sing-box where every one of them currently does.
//
// PKI (CA cert, server cert, server key, tls-crypt key) is generated by the
// panel and arrives pre-rendered as PEM text in Backend.config's "pki" object
// (see config.go's Config.PKI) - this package only ever consumes it as opaque
// text to inline into a rendered server config (render.go); it never
// generates or touches key material itself.
package openvpn

import (
	"context"
	"errors"
	"fmt"
	"log"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/pasarguard/node/common"
	"github.com/pasarguard/node/config"
	"github.com/pasarguard/node/pkg/stats"
)

// Backend is the OpenVPN-backed implementation of backend.Backend.
type Backend struct {
	instances map[string]*instanceProcess // tag -> instance, fixed for the Backend's lifetime
	order     []string                    // tags in tunIndex order, for deterministic iteration/logging

	version   string
	startTime time.Time
	logsChan  chan string

	statsTracker *stats.Tracker

	cancelFunc context.CancelFunc
	mu         sync.RWMutex
}

// New renders, applies NAT for, and starts every configured instance, syncs
// the initial user set into each instance's live auth store before starting
// it (so no user has to reconnect after a fresh boot to be recognized), and
// starts a background supervisor that restarts any instance that crashes.
func New(ctx context.Context, ovConfig *Config, users []*common.User, cfg *config.Config) (*Backend, error) {
	if ovConfig == nil {
		return nil, errors.New("openvpn config must not be nil")
	}
	if len(ovConfig.Instances) == 0 {
		return nil, errors.New("openvpn config: at least one instance is required")
	}

	executablePath := strings.TrimSpace(cfg.OpenVPNExecutablePath)
	if executablePath == "" {
		executablePath = "openvpn"
	}
	executableAbsolutePath, err := filepath.Abs(executablePath)
	if err != nil {
		return nil, err
	}

	baseDir, err := filepath.Abs(filepath.Join(cfg.GeneratedConfigPath, "openvpn"))
	if err != nil {
		return nil, err
	}

	bCtx, bCancel := context.WithCancel(context.Background())

	b := &Backend{
		instances:    make(map[string]*instanceProcess, len(ovConfig.Instances)),
		version:      detectVersion(executableAbsolutePath),
		startTime:    time.Now(),
		logsChan:     make(chan string, logBufferSizeOrDefault(cfg)),
		statsTracker: stats.New(),
		cancelFunc:   bCancel,
	}

	tunIndex := assignTunIndices(ovConfig.Instances)

	order := make([]string, 0, len(tunIndex))
	for tag := range tunIndex {
		order = append(order, tag)
	}
	sort.Slice(order, func(i, j int) bool { return tunIndex[order[i]] < tunIndex[order[j]] })
	b.order = order

	for _, inst := range ovConfig.Instances {
		b.instances[inst.Tag] = newInstanceProcess(inst, ovConfig.PKI, tunIndex[inst.Tag], baseDir, executableAbsolutePath, b.logsChan, cfg.StartupLogTailSize)
	}

	if len(users) > 0 {
		log.Printf("openvpn: syncing %d users on startup", len(users))
		b.syncAllUsers(users)
	} else {
		log.Println("openvpn: no users provided on startup")
	}

	for _, tag := range b.order {
		instance := b.instances[tag]
		if err := instance.Start(); err != nil {
			b.Shutdown()
			return nil, fmt.Errorf("openvpn: failed to start instance %q: %w", tag, err)
		}
		log.Printf("openvpn instance %q started (proto=%s port=%d tun=%d)", tag, instance.inst.Protocol, instance.inst.Port, instance.tunIndex)
	}

	go b.superviseInstances(bCtx)
	go b.sampleStatsPeriodically(bCtx, statsUpdateInterval(cfg))

	log.Println("openvpn started, Version:", b.version)

	return b, nil
}

func logBufferSizeOrDefault(cfg *config.Config) int {
	if cfg != nil && cfg.LogBufferSize > 0 {
		return cfg.LogBufferSize
	}
	return 1
}

func statsUpdateInterval(cfg *config.Config) time.Duration {
	seconds := 10
	if cfg != nil && cfg.StatsUpdateIntervalSeconds > 0 {
		seconds = cfg.StatsUpdateIntervalSeconds
	}
	return time.Duration(seconds) * time.Second
}

// assignTunIndices assigns each instance a stable "dev tunN" index, 0-based
// in tag-sorted order - deliberately independent of the JSON array order the
// panel happens to send instances in (which is not guaranteed stable across
// requests), so the same set of instance tags always gets the same tun
// devices across restarts.
func assignTunIndices(instances []*InstanceConfig) map[string]int {
	tags := make([]string, 0, len(instances))
	for _, inst := range instances {
		tags = append(tags, inst.Tag)
	}
	sort.Strings(tags)

	idx := make(map[string]int, len(tags))
	for i, tag := range tags {
		idx[tag] = i
	}
	return idx
}

// detectVersion best-effort parses "openvpn --version" output. Note openvpn
// exits non-zero for --version, so the error from Output() is intentionally
// ignored - stdout is still populated either way.
func detectVersion(executablePath string) string {
	out, _ := exec.Command(executablePath, "--version").Output()
	line, _, _ := strings.Cut(string(out), "\n")
	line = strings.TrimSpace(line)
	if line == "" {
		return "unknown"
	}
	fields := strings.Fields(line)
	if len(fields) >= 2 && strings.EqualFold(fields[0], "OpenVPN") {
		return fields[1]
	}
	return line
}

func (b *Backend) Started() bool {
	b.mu.RLock()
	defer b.mu.RUnlock()
	if len(b.instances) == 0 {
		return false
	}
	for _, instance := range b.instances {
		if !instance.Started() {
			return false
		}
	}
	return true
}

func (b *Backend) Version() string {
	b.mu.RLock()
	defer b.mu.RUnlock()
	return b.version
}

func (b *Backend) Logs() <-chan string {
	b.mu.RLock()
	defer b.mu.RUnlock()
	return b.logsChan
}

// Restart restarts every instance. Errors from individual instances are
// joined rather than short-circuiting, so one broken instance doesn't
// prevent the others from restarting.
func (b *Backend) Restart() error {
	b.mu.RLock()
	tags := append([]string(nil), b.order...)
	b.mu.RUnlock()

	var errs []error
	for _, tag := range tags {
		b.mu.RLock()
		instance := b.instances[tag]
		b.mu.RUnlock()
		if instance == nil {
			continue
		}
		if err := instance.Restart(); err != nil {
			errs = append(errs, fmt.Errorf("instance %q: %w", tag, err))
		}
	}
	return errors.Join(errs...)
}

func (b *Backend) Shutdown() {
	b.mu.Lock()
	defer b.mu.Unlock()

	if b.cancelFunc != nil {
		b.cancelFunc()
		b.cancelFunc = nil
	}

	for _, tag := range b.order {
		if instance, ok := b.instances[tag]; ok {
			instance.Stop()
		}
	}

	log.Println("openvpn shutdown complete")
}

// superviseInstances periodically restarts any instance that isn't running
// (e.g. after a crash), with per-instance exponential backoff so a
// persistently broken instance doesn't get restart-stormed - mirrors the
// spirit of sing-box's checkHealth (backend/singbox/jobs.go), adapted for N
// independently-supervised instances instead of one.
func (b *Backend) superviseInstances(ctx context.Context) {
	const (
		checkInterval = 3 * time.Second
		maxBackoff    = 60 * time.Second
	)

	backoff := make(map[string]time.Duration)
	nextAttempt := make(map[string]time.Time)

	for {
		select {
		case <-ctx.Done():
			return
		case <-time.After(checkInterval):
		}

		b.mu.RLock()
		tags := append([]string(nil), b.order...)
		b.mu.RUnlock()

		for _, tag := range tags {
			b.mu.RLock()
			instance := b.instances[tag]
			b.mu.RUnlock()
			if instance == nil {
				continue
			}
			if instance.Started() || instance.Restarting() || instance.Stopping() {
				continue
			}
			if t, ok := nextAttempt[tag]; ok && time.Now().Before(t) {
				continue
			}

			log.Printf("openvpn instance %q is not running, attempting restart", tag)
			if err := instance.Restart(); err != nil {
				cur := backoff[tag]
				if cur == 0 {
					cur = 2 * time.Second
				} else {
					cur *= 2
					if cur > maxBackoff {
						cur = maxBackoff
					}
				}
				backoff[tag] = cur
				nextAttempt[tag] = time.Now().Add(cur)
				log.Printf("openvpn instance %q restart failed, backing off %s: %v", tag, cur, err)
			} else {
				delete(backoff, tag)
				delete(nextAttempt, tag)
				log.Printf("openvpn instance %q restarted", tag)
			}
		}
	}
}

func (b *Backend) sampleStatsPeriodically(ctx context.Context, interval time.Duration) {
	if interval <= 0 {
		interval = 10 * time.Second
	}
	ticker := time.NewTicker(interval)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
			b.refreshUserStats()
		}
	}
}
